# 화폐와 통화량

## 화폐

- 화폐의 기능
시중에 돈이 지나치게 많으면 가치가 떨어져서 물가가 오르는 인플레이션이 발생 한다, 지나치게 적은 경우에는 경제활동이 위축되어 경기 침체가 발생 한다

수요와 공급 원칙에 의해서 돈이 풍부한 경우 금리가 하락하고 그 반대의 경우 금리가 오른 상태가 된다

- 화폐로 통용되는 것 들
물물교환 시절에는 조개가 화페로 쓰이기도 했으며 1960년대까지 우리나라는 쌀이 화폐를 대신 하기도 하였다
조개껍질 구슬 무멸, 노예
노예는 20세기 초까지 아프리카서부 지역에서 화폐의 기능을 가지고 있었다 
- 공급량이 한정되어 있어서 가치의 안정성을 가지고 있는 금을 금속화폐 라고도 한다
- 이후 정부가 법으로 화폐의 가치를 강제적으로 부여(Fiat Money)

back to R
금은 
우리는 앞에서 중앙은행이 법화제도의 운용을 책임지고 있다는 사실을 학습하였습니다. 또한 중앙은행은 물가안정을 통해 국가의 경제가 안정적으로 성장할 수 있도록 이바지할 의무도 있습니다. 이와 같은 측면에서 중앙은행은 통화발행 권한을 이용하여 앞서 학습한 경기변동에 대응하여 물가안정을 도모함으로써 경기안정화를 달성하기 위해 노력합니다. 이제 중앙은행이 화폐의 공급량인 통화량을 조절함으로써 어떻게 물가를 안정시키고 경기변동에 대응하는지를 알아보겠습니다. 경제규모에 비해 시중에 돈이 지나치게 많으면 그 가치가 떨어져 물가가 지속적으로 오르는 인플레이션이 발생하고, 반대로 지나치게 적은 경우에는 생산자금이 부족하게 되어 경제활동이 위축되는 경기침체가 발생합니다. 따라서 우리나라의 경우 돈의 양을 조절하는 책임을 지고 있는 한국은행은 몇 가지 수단을 사용해서 통화량을 적절하게 조정함으로써 화폐가치의 안정, 즉 물가안정에 힘쓰고 있습니다. 통화량을 조절하는데 있어 중요한 수단으로 활용되는 것에는 공개시장조작정책과 지급준비정책 그리고 대출정책(재할인정책) 등 3가지가 있습니다. 공개시장조작정책은 채권시장과 같은 금융시장에서 중앙은행이 금융기관을 상대로 국공채나 통화안정증권 등의 매매를 통해 통화량을 조절하는 정책을 말합니다. 중앙은행이 돈을 지불하고 민간금융기관으로부터 국공채를 매입하면 시중의 통화량이 증가하게 됩니다. 그리고 반대로 중앙은행이 돈을 받고 민간금융기관에 국공채를 매각하면 시중의 통화량이 감소하게 됩니다.

중앙은행이 법정지급준비율을 높이거나 낮춤으로써 통화량의 규모를 적절한 수준으로 조절하는 정책을 지급준비정책이라고 합니다. 그 구체적인 운용내용은 다음과 같습니다. 우리는 앞에서 은행들이 지급준비금을 보유한다는 사실을 알았고 또한 예금액 중 지급준비금으로 보유하는 비율과 예금통화 창출 규모간에는 반비례 관계가 있다는 사실도 학습했습니다. 그런데 중앙은행은 시중은행의 예금액 중 지급준비금 보유비율을 법령으로 규정할 수 있으며 이렇게 법령으로 강제된 지급준비금 보유비율을 법정지급준비율 이라고 합니다. 만일 중앙은행이 법정지급준비율을 높인다면 예금통화 창출 규모가 감소하여 시중의 통화량은 감소하게 됩니다. 반대로 중앙은행이 법정지급준비율을 낮춘다면 예금통화 창출규모가 증가하여 시중의 통화량은 증가하게 됩니다.
## 통화량 
대출정책이란 중앙은행이 민간은행에 빌려주는 자금에 대한 금리를 조정하여 통화량을 조절하는 정책을 말합니다. 그 구체적인 운용내용은 다음과 같습니다. 개인들이 부족한 자금을 은행에서 빌리듯이 민간 시중은행들도 부족한 자금을 중앙은행에서 빌립니다. 그리고 중앙은행은 돈을 빌려가는 민간은행에게 부과되는 대출금리를 조정하여 통화량을 조절합니다. 이 때 대출금리는 재할인금리라고도 부릅니다. 중앙은행이 대출금리를 낮추면 민간은행은 저렴한 비용으로 자금을 이용할 수 있게 됩니다. 따라서 중앙은행에서 더 많은 자금을 빌려갈 것이므로 시중에 통화량이 증가하게 됩니다. 반면에 중앙은행이 대출금리를 인상하면 민간 은행은 비싼 비용으로 자금을 이용해야 합니다. 그러면 민간은행은 중앙은행에게 자금을 빌려가지 않거나 기존에 빌렸던 자금을 상환할 것이므로 시중에 통화량이 감소하게 됩니다.

## 약속어음
- 강원도중도개발공사(GJC)가 증권사로부터 2,030억원의 자금을 차입함
- 중간에는 SPC인 GJC의 자회사가 자금을 차입하고 이를 근거로 ABCP를 발행 하였음
- 만기일인 2022.9.8 자에 동금액을 연장(roll-over)하려 증권사를 방문 하였으나,
- ABCP발행 자에 대한 보증을 섰던 지방정부인 강원도가 보증 연장에 대하여 불가 조치를 내림

