# 주식과 채권

## Primary market
발행시장이라고 하며 주식이나 채권을 회사로 부터 직접 취득 할 수 있다

## Secondary market
프라이머리 마켓에서 취득한 투자자자산은 2차시장 즉 세컨더리 마켓에서 이를 매각할 수 있고 발행시장에 참여 하지 못했던 사람들은 여기서 이차로 투자자산을 매수 한다

주식
회사가 사업을 하려면 돈이 필요하다. 친구에게 빌릴수도 있고 지인들을 통하여 돈을 모을 수도 있다

간편한 방법은 어떤 증서를 발행하고 이를 제3자(투자자)에게 매각한다면 짧은 시간에 필요한 자금을 만들 수 있을 것이다

사업초기, 즉 회사가 초기에 자본금을 납입하고 회사설립시기나 프로젝트를 발굴하고 이를 추진 하려 할때 주식을 공모한다. 공모란 불특정 다수인에게 주식을 매각 하는 방법이다

매각된 주식은 코스닥이나 유가증권시장에 등록하고 최초 투자자는 여기서 주식을 매각하여 시세 차익을 얻을 수 있다

회사는 공모를 통하여 자금을 모았고 투자자는 주식매각을 통하여 자기의 주머니를 두둑히 하게 되었다

initial public offering (IPO). As the name implies, an IPO is a company's first sale of stock to the public.

## 채권
회사는 증서를 발행하고 자금을 차입한다. 채권은 타인에 대한 부채증명서인 셈이다. IOU

주식과 달리 차입금에 대하여 이자를 지급하고 언제 돈을 갚겠다고 하는 만기일이 표시 되어 있다

정부에서 도서관을 짓고 항만을 건설하고, 고속도로를 새로 계획할때 채권을 발행하여 필요한 자금을 모을 수 있다

최초로 취득한 투자자는 증권사를 통하여 이를 매각하여 시세 차익을 얻을 수 있다

## 증서, 종이, 어음 (note, paper, commercial paper)
금액을 표시하고, 언제 까지 지불 하겠다는 만기일을 적고 누가 이 증서를 만들었는지 회사이름을 펴기 한다음에 그 옆에 회사의 도장을 찍 는다. 이 회사가 증서의 발행인이 된다. 발행인의 신용도가 약하여 만기일에 약속한 자금을 잔환하지 못할 위험이 있는 경우 증서 매입자 들은 불 안해 할 수 있다. 이를 보완하기 위하여 보증인인 제3자 회사가 가입 할 수 있으며 이를 보증인이라고 하며 발행인과 함께 즈서에 도장을 찍고 연대하여 돈을 갚을 채무를 진다

## 사업을 위한 필요 자금
회사가 돈이 필요한 경우 몇가지 방법을 생각 해 볼 수 있다

가지고 있는 여유자금을 이용 한다. 물건을 팔아 영업을 하며 생긴 이익금을 말 한다
친구, 집안친척 또는 가까운 지인에게 부탁 한다
회사소유권을 일부 넘겨주고 투자자를 유치 한다
은행에 가서 돈을 차입한다
모르는 사람들에게 주식을 발행하여 단시간에 대량 매각 하여 자금을 모은다 이때 투자자는 일정부분의 회사지분을 취득 하게 된다
채권을 발행 한다. 만기 때 되 갚는 다