# 은행 베이직

## 은행에 통장을 만드는 이유
* 보통예금 통장은 어떤 건가요?
* 적금통장 

## 금융기관이 하는 일    
* 은행
   * ATM 기를 이용할 수 있다
   * 체크카드(debit card) 발급
   * **체크카드 분실**의 경우 곧바로 은행에 신고한다. 전화 또는 은행 APP 이용하여 신고가능
   * 은행은 음식이나 옷 등 재화를 생산하지 않고 자동차대출(Car Loan), 주택대출(Home Mortage), 크레딧카드 서비스를 제공한다
   * 안전한 곳에 돈을 맡기기 위하여 또는 자동차를 구매하고 집을 장만하고 학자금대출 등을 하기 위하여 은행을 이용한다
<br/>  
* 협동조합(Credit Union)
   * 협동조합에서 통장을 만들어 예금을 하는 경우 협동조합의 소유자 중 한명이(owner-member) 된다는 것이다 
   * 회사의 형태와 다른 의미 
   * 조합원에게 일반적으로 예금금리는 높고 대출금리는 은행보다 낮을 수 있다
<br/>         
* 인터넷은행
   * 인터넷은행은 건물이나 지점을 만들지 않고 영업을 한다
   * 고정비에 대한 경비절감으로 위에서 언급한 금융기관보다 높은 예금이자, 낮은대출금리, 낮은 수수료를 부과 한다  
   * 단점은 금융 서비스를 기대하며 대면으로 상담 할 장소가 없으며 대여금고 를 이용할 수 도 없다
   * 여러분 들은 어떤 종류의 금융기관이 던지 선택할 수 있으며 단지 그 기관이 인가를 받은 정상적 회사인지 예금자보호제도는 갖춰쳐 있는지 확인이 필요 함 
   
## 통장종류 
* 저축이 목적인 경우
* 대출이 필요한 경우
* 가계자금 또는 기업운영용도의 자금이 필요한 경우 통장을 달리하며 이용한다
* Savings Account(이자가 붙는 예금) & Checking Account (수표발행 또는 debit card 이용하는 예금)
* 거래를 시작 할때 통장의 종류, 예금금리, 수수료 및 서비스종류를 잘 비교해 보고 금융기관을 선택하세요

## 통장개설 절차     
* 신분증(주민등록증, 학생증, 여권 등)
* 이메일주소
* 때때로 이름이 있는 공과금 청구내역 등

## 올바른 소비습관 만들기   
* ATM 에서 출금거래 내역이나 체크카드에서 돈이 인출될 때 통지내역에 주의 해야 함    
* 온라인으로도 반드시 확인 한다   
* 예금금액과 인출내용에 대해서 주의를 기울인다   
* **용돈이 어디에 주로 쓰였는지, 기록 하고 확인한다** 
<br/>    
출처 [Page One Economics(미국 FRB)](https://research.stlouisfed.org/publications/page1-econ/2020/10/01/banking-basics)  
기타 [청소년금융교육(한국은행)](http://www.bok.or.kr/portal/main/contents.do?menuNo=201040)        
