# 자동화와 최저임금

>1938년 최저임금 도입, 프랭클린루즈벨트 대통령
당시 25센트, 궁핍을끝내기 위해 소수에게 적용
현재 주정부의 최저임금정책 7.25달러, 2009년 마지막 개정
명목(nominal) 최저임금은 계속 상승했지만 실질 구매력은 상승못함 

## 교과서적 접근법

- 노동시장은 **공급측면(노동자)**와 **수요측면(그들을 원하는 회사)** 으로 구성 됨     
- 공급사이드 주어진 임금하에서 일을 하려는 의사가 있음    
- 수요사이드 주어진 임금하에서 노동자를 고용하려는 의사가 있음     
- 균형, 일정한 가격에서 We 생성, 일하려는 근로자의 숫자와 회사가 고용하려하는 숫자가 일치함    
- 정부에서 최저임금을 강제하는 경우, 균형가격 위에서 형성 최저임금은 price floor 역할을 하게 됨    
- 높은 임금을 노리고 덜숙련된 노동시장에 진입하여 공급이 늘어난다. 수요자는 노동자에게 - 지급되는 임금이 부담스러워서 채용을 줄이게 된다    
- 일단 높은 최저임금에서 채용된 사람들은 이익(beneficiaries)을 누리게 된다. 반면 - 그래프에서 보 듯이 일정 부분은 과다 공급으로 나타나게 된다     
- 이들은 현재 일자리 보다 많은 공급으로 실업으로 나타나게 된다     
    
- miss nuances(미묘한 차이)
- 최저임금을 도입하더라도 lay off 로 이어지진 않았다. Davis Card & Alan Kruger, 1990년대 뉴저지를 예로 들었음. 패스트푸드업계     
- 누가 이익을 보았나?    
  - 1.1백만명이 혜택을 보았음 . 이는 시간 임금자의 1.5%로 미미한 수준   
  - 45%는 25살이하 젊은이, 20%는 틴에이지. 가계의 주수입원은 아니지만 일을 통해서 경험을 쌓는다   

## Trade off   

### 찬성론자    
- 저소득 임금자에게 식량, 월세 등 필요한 생활비를 충당하며 삶의 질을 높인다
- 예를 들어 2025년 $25로 최저임금이 되는 경우 17백만명이 혜택을 누리고 빈곤층이 90만명 줄어 들게 된다
- 또한 근로자들의 사기를 진작하고 고용자의 제반비용(turn over & hiring/training cost)를 줄인다

### 반대론자    
- 15달러 최저임금은 저숙련 일자리를 줄여서 거기에서 일하는 사람들이 타격을 받게 된다   
- 그래서 1.4백만명이 일자리를 잃게 된다. 이는 0.9%이다    
- 경제학 적으로 근로자의 임금을 초과하는 이익(revenue)가 있을 때 일자리는 존재 할 수 있고 비로서 채용이 생긴다     
- 최저임금을 도입하는 경우 수익(revenue)이 노동비용을 따라가지 못 할 수 있다     
- 간단히 말해서 높은 임금을 주고 동수의 근로자를 유지는 불가능 하게 된다     
결국 저숙련노동자들의 실업으로 이어지게 된다    

- EITC (생략)    

### Automation and the Minimum wage     

- 자동화는 기구(apparatus), 공정, 어떤 기계로 인간의 노동을 대체할 수 있는 수단을 말한다    
- 새로운 것이 아니며 산업화시대 이후 꾸준히 영향을 기치고 있다       
- 로봇과 AI는 지금시대의 자동화로 생각 할 수 있다. 공상과학 속의 드로이드도 있지만 간단한 알고리즘을 이용한 기구도 있다   
- 예을 들어 집안의 온도를 조절하는 온도계도 로봇의 일종 일수 있다. 반복적인 일을 행하며 사람이 작동하는 것이 필요 없는 기계다   
- Physical Capital과 달리 로봇은 프로그램되어서 사람의 간섭없이 무한 반복이 가능 해진다 - 하는 일을 자동화 시켜보자, 우리 일은 여러가지 스텝으로 분리 할 수 있다. 반복적일 일 수록 자동화가 쉽다(susceptible to automation)   
- 우리가 하는 일을 자동화시켜보자. 일은 몇가지 구분 된 동작으로 이루 어져 있다   
- 사람이 할수 도 있고 기계(physical capital)를 이용하여 완료 되기도 한다   
- 정형화 되 있고 반복적 일은 좀더 자동화가 쉬울 수 있다    
- 기술이 발전하면서 사람과 자동화된 기계가 하는 일은 좀더 복잡하게 상호작용하며 업무를 마감한다   
- 자동차 조립라인을 생각해보자   
- 자도차산업 초기인 1900년대에는 작업장에 공구를 든 노동자들이 모든 과정을 담당 했다   
- 그러나 시간이 지나면서 웰딩이나, 페인팅은 지금 자동화된 기계가 담당 하고있다   
물론 좀더 복잡한 기술이 필요한 곳은 아직도 사람에 의해서 마무리 되고 있기 도 하다    

- 보완하고 대체한다     
  - 자본비용 : 기술이 발전하며 많은 부분에서 응용될 때 자본비용은 하락 하는 경향이 있다    
  - 노동비용 : 저숙련 노동자들의 임금은 당시의 노동시장환경이나, 정부의 정책, 또는 최저임금 때문에 높게 책정되는 경우가 있고 이는 다른 생산요소로 대체되는 경향이 있다    

## 자동화는 다음의 경향이 있다    
- 경제학적으로 보면 기계투입 단위당 비용이 노동투입 단위당 비용보다 저렴한 경우     
노동자를 기계로 대체하려 한다**    

-   marginal cost of producing goods with capital < marginal cost of producing goods with labor

- 최저임금상승은 회사가 새로운기술을 도입하여 기존의 노동자를 해고시키려는 유인을 제시한다        
- 즉 높은 임금은 노동비용을 상승시키고 전반적인 업무에 부담이 되는 경우 자동화로 변화되는 경우가 강하다     
- 최저임금 직종은 대부분 노동집약적 이며, 비숙련 일로 구성(low-skill tasks) 되어있다    
- 예를 들어 수퍼마켓의 셀프체크 레인이나 패스트푸드점의 디지털 키오스크 도입을 볼수 있다    
- 상승된 최저임금은 비숙련 노동자들의 고용을 줄이고 이는 대부분 노령 노동자, 여성 그외 사회적 약자의 채용을 감소 시키게 된다

## 미래를 준비   

- 인간의 노동력을 기계가 대신한다는 암울한 미래가 있지만 인간이 도리어 기계를 몰아 낼수 있는 서로 보완적인 관계가 있음을 알아야 한다   
- 저숙련노동자(low-skilled  workers)을 대신하는 자리에 높은 수준의 인간노동력이 대체 될수 있다         
- 엑셀은 계산원의 자리를 위협했지만 분석능력이 요구되는 회계처리가나 경영컨설턴트 들과 같은 높은 수준의 노동자들을 신규 창출 했다고 할 수 있다     
- 저숙련 노동자를 해고한 제조업체에서는 기계의 문제점을 진단하고, 유지하는 고급 기술자를 채용 할 필요가 대두 되었고 그러기 위해서는 이들에게 높은 수준의 임금을 제공 하여야 했다 
- 우리 들은 기계의 변화에 대체되(substituted)지 않는 도리어 보완이 필요한 능력을 개발해야 한다   
- 고급기술이나 교육을 필요로 하는 분야에서 일을 할수있어야 한다. develop human capital 기술에 대체 되지 않고   
- **권장되는 교육루트는 liberal art(논리적 사고를 기른다) 와 in science(수량적이고 기술적인 능력 함양을 위해) 의 복수 전공을 추천한다**   
- 여기서 경제학은  두 전공의 중간적인 위체에 있다고 할 수 있다. 인간과 조직의 역할을 설명하는 사회과학 분야이고 동시애 수학적 모델을 이용하여 이론을 설명하고 테스트 하기 때문이다      

## 결론   

- 최저임금은 몇가지 논쟁을 일으킨다    
  - 저임금 노동자에게 높은 임금을 주기도하지만 그 들의 고용을 감소 시키기도 한다    
  - 높아진 최저임금은 생산비용을 증가하고 이는 회사가 물건을 만드는 것을 회피하거나 조업 중단을 일으 키기도 한다   
  - 결국 상대적으로 비싸진 노동자들을 대체하여 자동화를 가속화 시키는 유인을 기업주에게 제공한다    
  - 그러나 자동화는 때로 고급인력을 필요로 해서 기회를 주기도 한다    
학생 들은 기계와 대체될수 있는 기술이 무엇인지 연구하고 준비하여 자동하시대를 살아 갈수 있는 미래를 준비하여야 한다  끝.   

**출처 : FRB's Page One Economics, May 2022년 자료**       
